/**
 * Phase 16 Stage 6 asset relay: worker → engine ephemeral bytes → local cache →
 * GET /api/jobs/:id/assets. Covers the happy path, the missing-bytes fallback
 * (placeholder), the opt-out (no manifest), and generate_images forwarding.
 */

import { describe, expect, it } from 'vitest';

import { makeHarness, waitFor, type Harness } from './harness.js';

async function waitCompleted(harness: Harness, jobId: string): Promise<Record<string, unknown>> {
  let last: Record<string, unknown> = {};
  try {
    await waitFor(async () => {
      const res = await harness.app.inject({ method: 'GET', url: `/api/jobs/${jobId}` });
      last = res.json();
      return (last.status as string) === 'COMPLETED';
    });
  } catch {
    throw new Error(`job ${jobId} never COMPLETED; last view: ${JSON.stringify(last)}`);
  }
  return last;
}

describe('image asset relay (Stage 6)', () => {
  it('forwards generate_images to the engine and serves relayed bytes', async () => {
    const harness = await makeHarness({ scenario: { mode: 'ok', assets: true } });
    try {
      const created = await harness.app.inject({
        method: 'POST',
        url: '/api/jobs',
        payload: { brief: 'Boutique hotel near the old town.', generateImages: true },
        headers: { 'idempotency-key': 'ia-1' },
      });
      expect(created.statusCode).toBe(202);
      const jobId = (created.json() as { jobId: string }).jobId;

      // Queue is paused in the harness: nothing processed yet, no assets.
      const mid = await harness.app.inject({ method: 'GET', url: `/api/jobs/${jobId}/assets` });
      expect((mid.json() as { assets: unknown[] }).assets).toEqual([]);

      await harness.resumeWorker();
      await waitCompleted(harness, jobId);

      // generate_images reached the engine contract.
      const calls = harness.fake!.calls;
      expect(calls.length).toBeGreaterThan(0);
      expect(calls[0].generate_images).toBe(true);

      const res = await harness.app.inject({ method: 'GET', url: `/api/jobs/${jobId}/assets` });
      const body = res.json() as { assets: Array<Record<string, unknown>> };
      expect(body.assets.length).toBe(2);
      for (const asset of body.assets) {
        expect(asset.ref).toMatch(/^asset:/);
        expect(asset.mime).toBe('image/png');
        expect(typeof asset.data_b64).toBe('string');
        expect((asset.data_b64 as string).length).toBeGreaterThan(0);
        expect(asset.source).toBe('generated');
      }
      const refs = body.assets.map((a) => a.ref as string);
      expect(refs).toContain('asset:hero-x');

      // Bytes are readable by the web later from the same store after COMPLETED.
      expect(harness.assets.list(jobId).length).toBe(2);
    } finally {
      await harness.close();
    }
  });

  it('serves an empty list when the engine bytes are gone (placeholder path)', async () => {
    const harness = await makeHarness({ scenario: { mode: 'ok', assets: true, assetsMissing: true } });
    try {
      const created = await harness.app.inject({
        method: 'POST',
        url: '/api/jobs',
        payload: { brief: 'A brief whose generated bytes are gone.', generateImages: true },
        headers: { 'idempotency-key': 'ia-2' },
      });
      const id = (created.json() as { jobId: string }).jobId;
      await harness.resumeWorker();
      await waitCompleted(harness, id);
      const res = await harness.app.inject({ method: 'GET', url: `/api/jobs/${id}/assets` });
      expect((res.json() as { assets: unknown[] }).assets).toEqual([]);
    } finally {
      await harness.close();
    }
  });

  it('returns an empty list when the job never opted into images', async () => {
    const harness = await makeHarness({ scenario: { mode: 'ok' } });
    try {
      const created = await harness.app.inject({
        method: 'POST',
        url: '/api/jobs',
        payload: { brief: 'No images here.' },
        headers: { 'idempotency-key': 'ia-3' },
      });
      const jobId = (created.json() as { jobId: string }).jobId;
      await harness.resumeWorker();
      await waitCompleted(harness, jobId);
      const res = await harness.app.inject({ method: 'GET', url: `/api/jobs/${jobId}/assets` });
      expect((res.json() as { assets: unknown[] }).assets).toEqual([]);
      // And the engine contract never asked for images.
      for (const call of harness.fake!.calls) {
        expect(call.generate_images).toBeUndefined();
      }
    } finally {
      await harness.close();
    }
  });
});