"""Stage 6 asset-renderer — raster image generation (Phase 16).

Runs after asset-planner (stage 5) inside the full generation pipeline. It is
a code stage, not a free-typed LLM stage: prompts are deterministic functions
of the asset-planner requirement (subject / orientation / tone).

Honest-failure posture:
- per-image bounded failure: a non-ok ImageResult becomes an E-IMG-001 warning
  issue and the logical ref simply keeps the web's deterministic placeholder —
  the job still COMPLETES (a broken asset is not a fake-success page);
- the feature is OFF unless AI_IMAGE_PROVIDER is enabled AND the request opted
  in; when off the stage returns an empty success (no stage drift);
- generated bytes land in the ephemeral JobAssetStore (never the DB); only the
  manifest refs travel in JobResult.assets.
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from typing import Any

from app.config import Settings
from app.contracts import GenerationAttempt, Outcome, StageResult, Usage
from app.core.errors import RoutingConfigError
from app.cost.ledger import JobLedger
from app.providers.factory import ProviderRegistry
from app.providers.protocol import ImageResult
from app.routing.config import RoutingConfig

IMAGE_STAGE = "asset-renderer"
IMAGE_ISSUE_RULE = "E-IMG-001"
_GENERATED_KINDS = ("image", "illustration")
_OG_REQUIREMENT_ID = "og"
# OG/Social share raster aspect: square 1:1, native 1024px (vendors downscale).
_OG_SIZE = "1024x1024"


@dataclass(frozen=True)
class SuppliedImage:
    """A real product raster carried into the job (product-link generation).

    The stage uses it verbatim (no model call) instead of generating a
    placeholder lookalike; manifest refs stay logical ``asset:<requirement>``.
    """

    ref: str
    mime: str
    data: bytes

_TONE_STYLE: dict[str, str] = {
    "warm-professional": "warm, professional, softly lit, photo-realistic",
    "cool-modern": "cool tones, clean, modern, photo-realistic",
    "bold-creative": "bold colors, dynamic composition, editorial photography",
    "minimal-clean": "minimal, clean background, soft shadows, photo-realistic",
    "friendly-casual": "bright, friendly, natural light, candid",
}


class AssetRenderer:
    def __init__(self, *, routing: RoutingConfig, settings: Settings, providers: ProviderRegistry) -> None:
        self.routing = routing
        self.settings = settings
        self.providers = providers

    def enabled(self) -> bool:
        """Stage 6 runs only when a provider is configured AND the routing
        config declares an images: section."""
        return self.settings.image_provider in ("stub", "huggingface", "pollinations") and bool(self.routing.images)

    async def render(
        self,
        *,
        requirements: list[dict[str, Any]],
        tone: str | None,
        ledger: JobLedger,
        supplied: list[SuppliedImage] | None = None,
    ) -> tuple[StageResult, list[dict[str, Any]]]:
        """Generate raster assets for the planner's `image`/`illustration`
        requirements. Returns (StageResult, blobs) — blobs are the raw bytes
        for the pipeline to stash in the ephemeral JobAssetStore.

        `supplied` (product-link generation, Phase 16 part 2) short-circuits
        the model call: those real product rasters are used verbatim, in
        planner order, and generation covers the remaining requirements."""
        blobs: list[dict[str, Any]] = []
        empty = StageResult(stage=IMAGE_STAGE, ok=True, data={"images": []})
        if not self.enabled():
            return empty, blobs
        try:
            provider = self.providers.image_provider()
            image_def = self.routing.image()
        except (RoutingConfigError, ValueError):
            return empty, blobs
        if provider is None:
            return empty, blobs

        if getattr(provider, "name", "") == "pollinations":
            model_id = self.settings.image_pollinations_model or "pollinations"
        else:
            model_id = self.settings.image_hf_model or image_def.model_id
        selected = [
            r
            for r in requirements
            if isinstance(r, dict) and r.get("kind") in _GENERATED_KINDS and isinstance(r.get("id"), str) and r["id"].strip()
        ][: self.settings.image_max]

        try:
            source_images = (supplied or [])[: self.settings.image_max]
        except TypeError:
            source_images = []
        supplied_iter = iter(source_images)

        attempts: list[GenerationAttempt] = []
        issues: list[dict[str, Any]] = []
        manifest: list[dict[str, Any]] = []

        for i, req in enumerate(selected, start=1):
            rid = req["id"]
            prompt = self._prompt(subject=req.get("subject", ""), orientation=req.get("orientation", "landscape"), kind=req.get("kind", "image"), tone=tone)
            started = time.perf_counter()

            supplied_image = next(supplied_iter, None)
            if supplied_image is not None:
                if len(supplied_image.data) > self.settings.image_max_bytes:
                    issues.append(
                        {
                            "severity": "warning",
                            "ruleId": IMAGE_ISSUE_RULE,
                            "path": f"/images/{rid}",
                            "message": f"supplied product image exceeds the {self.settings.image_max_bytes}-byte cap — placeholder will be used",
                        }
                    )
                    continue
                result = ImageResult(ok=True, data=bytes(supplied_image.data), mime=supplied_image.mime, model="supplied", latency_ms=0.0, message="")
                cost = 0.0
                source = "supplied"
            else:
                try:
                    result = await provider.generate(prompt=prompt, size=self._size_for(req, image_def.size))
                except Exception as exc:  # noqa: BLE001 — bounded per-image outcome, never a job-killer
                    result = ImageResult(ok=False, message=f"image provider raised: {exc}", model=model_id, latency_ms=(time.perf_counter() - started) * 1000.0)
                cost = image_def.cost_per_image if result.ok and result.data else 0.0
                source = "generated"

            attempt = GenerationAttempt(
                stage=IMAGE_STAGE,
                attempt_number=i,
                prompt_ref="supplied@product" if supplied_image is not None else f"image@{model_id}",
                model_class="supplied" if supplied_image is not None else "image",
                provider=getattr(provider, "name", "?") if supplied_image is None else "product",
                model_id="supplied" if supplied_image is not None else model_id,
                usage=Usage(0, 0),
                cost_usd=cost,
                latency_ms=result.latency_ms,
                outcome=Outcome.ok if result.ok else Outcome.provider_error,
                validation_issues=[
                    {"severity": "warning", "ruleId": IMAGE_ISSUE_RULE, "path": f"/images/{rid}", "message": result.message or "image generation failed — placeholder will be used"}
                ]
                if not result.ok
                else [],
            )
            ledger.record(attempt)
            attempts.append(attempt)

            if result.ok and result.data and len(result.data) <= self.settings.image_max_bytes:
                data = bytes(result.data)
                ref = f"asset:{rid}"
                manifest.append({"ref": ref, "requirement_id": rid, "mime": result.mime, "size_bytes": len(data), "source": source})
                blobs.append({"ref": ref, "mime": result.mime, "data": data})
            elif result.ok:
                issues.append(
                    {
                        "severity": "warning",
                        "ruleId": IMAGE_ISSUE_RULE,
                        "path": f"/images/{rid}",
                        "message": f"generated image exceeds the {self.settings.image_max_bytes}-byte cap — placeholder will be used",
                    }
                )
            else:
                issues.append(
                    {
                        "severity": "warning",
                        "ruleId": IMAGE_ISSUE_RULE,
                        "path": f"/images/{rid}",
                        "message": result.message or "image generation failed — placeholder will be used",
                    }
                )

        await self._generate_og(
            provider=provider,
            requirements=selected,
            subject_hint=selected[0].get("subject") if selected else None,
            tone=tone,
            ledger=ledger,
            blobs=blobs,
            manifest=manifest,
            attempts=attempts,
            issues=issues,
            supplied=supplied,
        )

        stage = StageResult(stage=IMAGE_STAGE, ok=True, data={"images": manifest}, attempts=attempts, issues=issues)
        if issues:
            stage.draft = True
        return stage, blobs

    async def _generate_og(
        self,
        *,
        provider: Any,
        requirements: list[dict[str, Any]],
        subject_hint: str | None,
        tone: str | None,
        ledger: JobLedger,
        blobs: list[dict[str, Any]],
        manifest: list[dict[str, Any]],
        attempts: list[GenerationAttempt],
        issues: list[dict[str, Any]],
        supplied: list[SuppliedImage] | None = None,
    ) -> None:
        """Generate a dedicated square OG raster (1:1) appended to the manifest.

        Real product rasters win first (product-link generation, Phase 16
        part 2): the share card reuses the SECOND product raster — the first
        already fronts the hero — falling back to the first, exactly the PAGE3
        ``image.ts`` pattern. A real product photo is the best og:image there
        is, and it costs zero vendor calls. When no product raster fits, the
        stage generates a fresh square tile through the provider.

        Run only for the real providers and only when at least one section asset
        was produced (an og without content pixels is not worth a vendor call).
        The blob ref is ``asset:og``; schema_builder wires it into
        ``page.seo.ogImageRef``. Bounded failure, E-IMG-001 posture: a failed og
        never fails the stage — the ref simply stays unbound (no og meta).
        """
        og_ref = f"asset:{_OG_REQUIREMENT_ID}"
        if getattr(provider, "name", "") != "stub":
            provided = supplied or []
            candidate = provided[1] if len(provided) > 1 else (provided[0] if provided else None)
            if candidate is not None and len(candidate.data) <= self.settings.image_max_bytes:
                manifest.append(
                    {
                        "ref": og_ref,
                        "requirement_id": _OG_REQUIREMENT_ID,
                        "mime": candidate.mime,
                        "size_bytes": len(candidate.data),
                        "source": "supplied",
                    }
                )
                blobs.append({"ref": og_ref, "mime": candidate.mime, "data": bytes(candidate.data)})
                attempts.append(
                    GenerationAttempt(
                        stage=IMAGE_STAGE,
                        attempt_number=len(attempts) + 1,
                        prompt_ref="supplied@product",
                        model_class="supplied",
                        provider="product",
                        model_id="supplied",
                        usage=Usage(0, 0),
                        cost_usd=0.0,
                        latency_ms=0.0,
                        outcome=Outcome.ok,
                        validation_issues=[],
                    )
                )
                ledger.record(attempts[-1])
                return

        if not manifest or getattr(provider, "name", "") == "stub":
            return
        subject = (subject_hint or "").strip() or "the page hero visual from the landing page brief"
        prompt = self._prompt(subject=subject, orientation="square", kind="image", tone=tone)
        started = time.perf_counter()
        try:
            result = await provider.generate(prompt=prompt, size=_OG_SIZE)
        except Exception as exc:  # noqa: BLE001 — bounded per-image outcome
            result = ImageResult(ok=False, message=f"og image provider raised: {exc}", model="pollinations", latency_ms=(time.perf_counter() - started) * 1000.0)
        cost = 0.0
        og_ok = bool(result.ok and result.data and len(result.data) <= self.settings.image_max_bytes)
        if og_ok:
            cost = self.routing.image().cost_per_image if self.routing.images else 0.0
            manifest.append({"ref": og_ref, "requirement_id": _OG_REQUIREMENT_ID, "mime": result.mime, "size_bytes": len(result.data), "source": "generated"})
            blobs.append({"ref": og_ref, "mime": result.mime, "data": bytes(result.data)})
        else:
            issues.append(
                {
                    "severity": "warning",
                    "ruleId": IMAGE_ISSUE_RULE,
                    "path": "/og",
                    "message": result.message or "og image generation failed — no social-share asset",
                }
            )
        attempts.append(
            GenerationAttempt(
                stage=IMAGE_STAGE,
                attempt_number=len(attempts) + 1,
                prompt_ref=f"og@{self.settings.image_pollinations_model or 'pollinations'}",
                model_class="image",
                provider=getattr(provider, "name", "?"),
                model_id=self.settings.image_pollinations_model or "pollinations",
                usage=Usage(0, 0),
                cost_usd=cost,
                latency_ms=result.latency_ms,
                outcome=Outcome.ok if og_ok else Outcome.provider_error,
                validation_issues=[
                    {"severity": "warning", "ruleId": IMAGE_ISSUE_RULE, "path": "/og", "message": result.message or "og image generation failed — no social-share asset"}
                ]
                if not og_ok
                else [],
            )
        )
        ledger.record(attempts[-1])

    def _size_for(self, req: dict[str, Any], fallback: str) -> str:
        """Orientation-aware generation size per asset requirement.

        Landscape sections (hero split/carousel, full-width gallery) render at
        3:2 with cover-crop — a square 1024px source upscales and blurs, so the
        native landscape 1536x1024 wins. An explicit AI_IMAGE_SIZE unwins the
        defaults; an unknown orientation falls back to the configured size."""
        if self.settings.image_size:
            return self.settings.image_size
        orientation = str(req.get("orientation", "")).lower()
        if orientation == "portrait":
            return "1024x1536"
        if orientation == "square":
            return "1344x1344"
        if orientation == "landscape":
            return "1536x1024"
        return fallback

    def _prompt(self, *, subject: str, orientation: str, kind: str, tone: str | None) -> str:
        style = _TONE_STYLE.get(tone or "", "professional, photo-realistic")
        prefix = "Flat illustration of " if kind == "illustration" else "High-quality photograph of "
        return f"{prefix}{subject or 'the subject from the landing page brief'}. {style}. Orientation: {orientation}."