"""Stage 6 asset-renderer — raster image generation (Phase 16).

Runs after asset-planner (stage 5) inside the full generation pipeline. It is
a code stage, not a free-typed LLM stage: prompts are deterministic functions
of the asset-planner requirement (subject / orientation / tone).

Honest-failure posture:
- per-image bounded failure: a non-ok ImageResult becomes an E-IMG-001 warning
  issue and the logical ref simply keeps the web's deterministic placeholder —
  the job still COMPLETES (a broken asset is not a fake-success page);
- the feature is OFF unless AI_IMAGE_PROVIDER is enabled AND the request opted
  in; when off the stage returns an empty success (no stage drift);
- generated bytes land in the ephemeral JobAssetStore (never the DB); only the
  manifest refs travel in JobResult.assets.
"""

from __future__ import annotations

import time
from typing import Any

from app.config import Settings
from app.contracts import GenerationAttempt, Outcome, StageResult, Usage
from app.core.errors import RoutingConfigError
from app.cost.ledger import JobLedger
from app.providers.factory import ProviderRegistry
from app.providers.protocol import ImageResult
from app.routing.config import RoutingConfig

IMAGE_STAGE = "asset-renderer"
IMAGE_ISSUE_RULE = "E-IMG-001"
_GENERATED_KINDS = ("image", "illustration")

_TONE_STYLE: dict[str, str] = {
    "warm-professional": "warm, professional, softly lit, photo-realistic",
    "cool-modern": "cool tones, clean, modern, photo-realistic",
    "bold-creative": "bold colors, dynamic composition, editorial photography",
    "minimal-clean": "minimal, clean background, soft shadows, photo-realistic",
    "friendly-casual": "bright, friendly, natural light, candid",
}


class AssetRenderer:
    def __init__(self, *, routing: RoutingConfig, settings: Settings, providers: ProviderRegistry) -> None:
        self.routing = routing
        self.settings = settings
        self.providers = providers

    def enabled(self) -> bool:
        """Stage 6 runs only when a provider is configured AND the routing
        config declares an images: section."""
        return self.settings.image_provider in ("stub", "huggingface") and bool(self.routing.images)

    async def render(
        self,
        *,
        requirements: list[dict[str, Any]],
        tone: str | None,
        ledger: JobLedger,
    ) -> tuple[StageResult, list[dict[str, Any]]]:
        """Generate raster assets for the planner's `image`/`illustration`
        requirements. Returns (StageResult, blobs) — blobs are the raw bytes
        for the pipeline to stash in the ephemeral JobAssetStore."""
        blobs: list[dict[str, Any]] = []
        empty = StageResult(stage=IMAGE_STAGE, ok=True, data={"images": []})
        if not self.enabled():
            return empty, blobs
        try:
            provider = self.providers.image_provider()
            image_def = self.routing.image()
        except (RoutingConfigError, ValueError):
            return empty, blobs
        if provider is None:
            return empty, blobs

        model_id = self.settings.image_hf_model or image_def.model_id
        size = self.settings.image_size or image_def.size
        selected = [
            r
            for r in requirements
            if isinstance(r, dict) and r.get("kind") in _GENERATED_KINDS and isinstance(r.get("id"), str) and r["id"].strip()
        ][: self.settings.image_max]

        attempts: list[GenerationAttempt] = []
        issues: list[dict[str, Any]] = []
        manifest: list[dict[str, Any]] = []

        for i, req in enumerate(selected, start=1):
            rid = req["id"]
            prompt = self._prompt(subject=req.get("subject", ""), orientation=req.get("orientation", "landscape"), kind=req.get("kind", "image"), tone=tone)
            started = time.perf_counter()
            try:
                result = await provider.generate(prompt=prompt, size=size)
            except Exception as exc:  # noqa: BLE001 — bounded per-image outcome, never a job-killer
                result = ImageResult(ok=False, message=f"image provider raised: {exc}", model=model_id, latency_ms=(time.perf_counter() - started) * 1000.0)

            cost = image_def.cost_per_image if result.ok and result.data else 0.0
            attempt = GenerationAttempt(
                stage=IMAGE_STAGE,
                attempt_number=i,
                prompt_ref=f"image@{model_id}",
                model_class="image",
                provider=getattr(provider, "name", "?"),
                model_id=model_id,
                usage=Usage(0, 0),
                cost_usd=cost,
                latency_ms=result.latency_ms,
                outcome=Outcome.ok if result.ok else Outcome.provider_error,
                validation_issues=[
                    {"severity": "warning", "ruleId": IMAGE_ISSUE_RULE, "path": f"/images/{rid}", "message": result.message or "image generation failed — placeholder will be used"}
                ]
                if not result.ok
                else [],
            )
            ledger.record(attempt)
            attempts.append(attempt)

            if result.ok and result.data and len(result.data) <= self.settings.image_max_bytes:
                data = bytes(result.data)
                ref = f"asset:{rid}"
                manifest.append({"ref": ref, "requirement_id": rid, "mime": result.mime, "size_bytes": len(data), "source": "generated"})
                blobs.append({"ref": ref, "mime": result.mime, "data": data})
            elif result.ok:
                issues.append(
                    {
                        "severity": "warning",
                        "ruleId": IMAGE_ISSUE_RULE,
                        "path": f"/images/{rid}",
                        "message": f"generated image exceeds the {self.settings.image_max_bytes}-byte cap — placeholder will be used",
                    }
                )
            else:
                issues.append(
                    {
                        "severity": "warning",
                        "ruleId": IMAGE_ISSUE_RULE,
                        "path": f"/images/{rid}",
                        "message": result.message or "image generation failed — placeholder will be used",
                    }
                )

        stage = StageResult(stage=IMAGE_STAGE, ok=True, data={"images": manifest}, attempts=attempts, issues=issues)
        if issues:
            stage.draft = True
        return stage, blobs

    def _prompt(self, *, subject: str, orientation: str, kind: str, tone: str | None) -> str:
        style = _TONE_STYLE.get(tone or "", "professional, photo-realistic")
        prefix = "Flat illustration of " if kind == "illustration" else "High-quality photograph of "
        return f"{prefix}{subject or 'the subject from the landing page brief'}. {style}. Orientation: {orientation}."